inherit_gem:
  rubocop-inst:
    - rubocop.yml
    - rubocop-rspec.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

RSpec/IndexedLet:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
